"""Feature-facing ports for meals."""

from __future__ import annotations

from typing import Protocol


class MealStorePort(Protocol):
    def save_meal_observation(self, observation: object) -> None: ...
    def save_meal_candidate(self, record: object) -> None: ...
    def get_meal_candidate(self, user_id: str, candidate_id: str) -> object | None: ...
    def save_validated_meal_event(self, event: object) -> None: ...
    def list_validated_meal_events(self, user_id: str) -> list[object]: ...
    def get_validated_meal_event(self, user_id: str, event_id: str) -> object | None: ...
    def save_nutrition_risk_profile(self, profile: object) -> None: ...
    def list_nutrition_risk_profiles(self, user_id: str) -> list[object]: ...
    def get_nutrition_risk_profile(self, user_id: str, event_id: str) -> object | None: ...


class FoodStorePort(Protocol):
    def list_canonical_foods(self, *, locale: str, limit: int = 500) -> list[object]: ...
    def find_food_by_name(self, *, locale: str, name: str) -> object | None: ...
