"""map_remaining_entities

Revision ID: 65e0dd6d9d4b
Revises: 009c02741c3e
Create Date: 2026-03-26 22:05:23.202616

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '65e0dd6d9d4b'
down_revision: str | Sequence[str] | None = '009c02741c3e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_outbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('payload', sa.JSON(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('alert_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('sink',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('severity',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('correlation_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('next_attempt_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('last_error',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('lease_owner',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('lease_until',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('idempotency_key',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_alert_outbox_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_outbox_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_outbox_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_outbox_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_outbox_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_outbox_type'), ['type'], unique=False)
        batch_op.drop_column('payload_json')

    with op.batch_alter_table('biomarker_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('value',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('unit',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('reference_range',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('measured_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('source_doc_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_biomarker_readings_measured_at'), ['measured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_biomarker_readings_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_biomarker_readings_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])

    with op.batch_alter_table('meal_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('meal_state', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('meal_perception', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('enriched_event', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('media_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('embedding_v1', sa.JSON(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('captured_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('analysis_version',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_meal_records_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_records_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])
        batch_op.drop_column('meal_state_json')
        batch_op.drop_column('meal_perception_json')
        batch_op.drop_column('enriched_event_json')

    with op.batch_alter_table('medication_adherence_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('regimen_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('reminder_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('scheduled_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('taken_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('metadata_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_medication_adherence_events_regimen_id'), ['regimen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_adherence_events_reminder_id'), ['reminder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_adherence_events_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_adherence_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_adherence_events_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'medication_regimens', ['regimen_id'], ['id'])
        batch_op.create_foreign_key(None, 'reminder_events', ['reminder_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])

    with op.batch_alter_table('medication_regimens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('time_rules', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('slot_scope', sa.JSON(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('medication_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('canonical_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('dosage_text',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('timing_type',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('frequency_type',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("'fixed_time'"))
        batch_op.alter_column('fixed_time',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('instructions_text',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('source_type',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("'manual'"))
        batch_op.alter_column('source_filename',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('source_hash',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('timezone',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("'Asia/Singapore'"))
        batch_op.alter_column('parse_confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_medication_regimens_medication_name'), ['medication_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_regimens_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])
        batch_op.drop_column('time_rules_json')
        batch_op.drop_column('slot_scope_json')

    with op.batch_alter_table('reminder_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channels', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('schedule', sa.JSON(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('regimen_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('reminder_type',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('body',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('medication_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('dosage_text',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('route',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('instructions_text',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('special_notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('treatment_duration',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('timezone',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_reminder_definitions_user_active'))
        batch_op.create_index(batch_op.f('ix_reminder_definitions_regimen_id'), ['regimen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_definitions_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])
        batch_op.drop_column('schedule_json')
        batch_op.drop_column('channels_json')

    with op.batch_alter_table('reminder_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('reminder_definition_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('occurrence_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('regimen_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('reminder_type',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("'medication'"))
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("'Medication Reminder'"))
        batch_op.alter_column('body',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('medication_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('scheduled_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('sent_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_reminders_user_time'))
        batch_op.create_index(batch_op.f('ix_reminder_events_occurrence_id'), ['occurrence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_events_regimen_id'), ['regimen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_events_reminder_definition_id'), ['reminder_definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_events_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_events_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'reminder_occurrences', ['occurrence_id'], ['id'])
        batch_op.create_foreign_key(None, 'medication_regimens', ['regimen_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'reminder_definitions', ['reminder_definition_id'], ['id'])
        batch_op.drop_column('ack_at')
        batch_op.drop_column('dosage_text')
        batch_op.drop_column('slot')
        batch_op.drop_column('meal_confirmation')
        batch_op.drop_column('status')

    with op.batch_alter_table('reminder_occurrences', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
        batch_op.alter_column('reminder_definition_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('scheduled_for',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('trigger_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('action_outcome',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('acted_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('last_delivery_status',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('metadata_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_reminder_occurrences_user_status_time'))
        batch_op.create_index(batch_op.f('ix_reminder_occurrences_reminder_definition_id'), ['reminder_definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_occurrences_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_occurrences_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_occurrences_trigger_at'), ['trigger_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_occurrences_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'reminder_definitions', ['reminder_definition_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])

    with op.batch_alter_table('symptom_checkins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('symptom_codes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('context', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('safety', sa.JSON(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('recorded_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('free_text',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_symptom_checkins_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_symptom_checkins_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_symptom_checkins_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])
        batch_op.drop_column('safety_json')
        batch_op.drop_column('context_json')
        batch_op.drop_column('symptom_codes_json')

    with op.batch_alter_table('workflow_timeline_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('payload', sa.JSON(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('event_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
        batch_op.alter_column('event_type',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('workflow_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('request_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('correlation_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_workflow_timeline_events_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_timeline_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_timeline_events_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_timeline_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_timeline_events_workflow_name'), ['workflow_name'], unique=False)
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])
        batch_op.drop_column('payload_json')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_timeline_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payload_json', sa.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_workflow_timeline_events_workflow_name'))
        batch_op.drop_index(batch_op.f('ix_workflow_timeline_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_timeline_events_request_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_timeline_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_workflow_timeline_events_correlation_id'))
        batch_op.alter_column('user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('correlation_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('request_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('workflow_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('event_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('event_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('payload')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('symptom_checkins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symptom_codes_json', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('context_json', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('safety_json', sa.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_symptom_checkins_user_id'))
        batch_op.drop_index(batch_op.f('ix_symptom_checkins_severity'))
        batch_op.drop_index(batch_op.f('ix_symptom_checkins_recorded_at'))
        batch_op.alter_column('free_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('recorded_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('safety')
        batch_op.drop_column('context')
        batch_op.drop_column('symptom_codes')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('reminder_occurrences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reminder_occurrences_user_id'))
        batch_op.drop_index(batch_op.f('ix_reminder_occurrences_trigger_at'))
        batch_op.drop_index(batch_op.f('ix_reminder_occurrences_status'))
        batch_op.drop_index(batch_op.f('ix_reminder_occurrences_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_reminder_occurrences_reminder_definition_id'))
        batch_op.create_index(batch_op.f('idx_reminder_occurrences_user_status_time'), ['user_id', 'status', 'trigger_at'], unique=False)
        batch_op.alter_column('metadata_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('last_delivery_status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('acted_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('action_outcome',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('action',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('trigger_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('scheduled_for',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('reminder_definition_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('reminder_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('meal_confirmation', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('slot', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('dosage_text', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('ack_at', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reminder_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_reminder_events_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_reminder_events_reminder_definition_id'))
        batch_op.drop_index(batch_op.f('ix_reminder_events_regimen_id'))
        batch_op.drop_index(batch_op.f('ix_reminder_events_occurrence_id'))
        batch_op.create_index(batch_op.f('idx_reminders_user_time'), ['user_id', 'scheduled_at'], unique=False)
        batch_op.alter_column('sent_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('scheduled_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('medication_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('body',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'Medication Reminder'"))
        batch_op.alter_column('reminder_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'medication'"))
        batch_op.alter_column('regimen_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('occurrence_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('reminder_definition_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('acknowledged_at')
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('reminder_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channels_json', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('schedule_json', sa.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reminder_definitions_user_id'))
        batch_op.drop_index(batch_op.f('ix_reminder_definitions_regimen_id'))
        batch_op.create_index(batch_op.f('idx_reminder_definitions_user_active'), ['user_id', 'active', 'updated_at'], unique=False)
        batch_op.alter_column('active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('timezone',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('treatment_duration',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('special_notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('instructions_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('route',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('dosage_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('medication_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('body',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('source',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('reminder_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('regimen_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('schedule')
        batch_op.drop_column('channels')

    with op.batch_alter_table('medication_regimens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot_scope_json', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('time_rules_json', sa.TEXT(), server_default=sa.text("'[]'"), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_medication_regimens_user_id'))
        batch_op.drop_index(batch_op.f('ix_medication_regimens_medication_name'))
        batch_op.alter_column('active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('parse_confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('timezone',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'Asia/Singapore'"))
        batch_op.alter_column('end_date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('source_hash',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('source_filename',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('source_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'manual'"))
        batch_op.alter_column('instructions_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fixed_time',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('frequency_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'fixed_time'"))
        batch_op.alter_column('timing_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('dosage_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('canonical_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('medication_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('slot_scope')
        batch_op.drop_column('time_rules')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('medication_adherence_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_medication_adherence_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_medication_adherence_events_status'))
        batch_op.drop_index(batch_op.f('ix_medication_adherence_events_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_medication_adherence_events_reminder_id'))
        batch_op.drop_index(batch_op.f('ix_medication_adherence_events_regimen_id'))
        batch_op.alter_column('metadata_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('source',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('taken_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('scheduled_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('reminder_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('regimen_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('meal_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enriched_event_json', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('meal_perception_json', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('meal_state_json', sa.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_meal_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_meal_records_captured_at'))
        batch_op.alter_column('analysis_version',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('source',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('captured_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('embedding_v1')
        batch_op.drop_column('media_url')
        batch_op.drop_column('enriched_event')
        batch_op.drop_column('meal_perception')
        batch_op.drop_column('meal_state')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('biomarker_readings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_biomarker_readings_user_id'))
        batch_op.drop_index(batch_op.f('ix_biomarker_readings_name'))
        batch_op.drop_index(batch_op.f('ix_biomarker_readings_measured_at'))
        batch_op.alter_column('source_doc_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('measured_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('reference_range',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('unit',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('value',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('alert_outbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payload_json', sa.TEXT(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_alert_outbox_type'))
        batch_op.drop_index(batch_op.f('ix_alert_outbox_state'))
        batch_op.drop_index(batch_op.f('ix_alert_outbox_severity'))
        batch_op.drop_index(batch_op.f('ix_alert_outbox_next_attempt_at'))
        batch_op.drop_index(batch_op.f('ix_alert_outbox_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_alert_outbox_correlation_id'))
        batch_op.alter_column('idempotency_key',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('lease_until',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('lease_owner',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('last_error',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('next_attempt_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('state',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('correlation_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('severity',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('sink',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('alert_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('payload')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
