"""initial_schema_with_normalization

Revision ID: a70ccb965b37
Revises:
Create Date: 2026-03-28 10:28:10.275082

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'a70ccb965b37'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
