"""Application ports for household."""

from typing import Any, Protocol


class HouseholdStorePort(Protocol):
    def get_household_for_user(self, user_id: str) -> dict[str, Any] | None: ...
    def get_household_by_id(self, household_id: str) -> dict[str, Any] | None: ...
    def create_household(self, *, owner_user_id: str, owner_display_name: str, name: str) -> dict[str, Any]: ...
    def list_members(self, household_id: str) -> list[dict[str, Any]]: ...
    def get_member_role(self, household_id: str, user_id: str) -> str | None: ...
    def rename_household(self, *, household_id: str, name: str) -> dict[str, Any] | None: ...
    def create_invite(self, *, household_id: str, created_by_user_id: str) -> dict[str, Any]: ...
    def join_by_invite(
        self, *, code: str, user_id: str, display_name: str
    ) -> tuple[dict[str, Any], bool] | None: ...
    def remove_member(self, *, household_id: str, user_id: str) -> bool: ...
