"""
Define persistence backend protocols.

This module provides structural protocols for domain-specific repositories.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol


class MealRepositoryProtocol(Protocol):
    def save_meal_record(self, record: Any) -> None: ...
    def list_meal_records(self, user_id: str) -> list[Any]: ...
    def get_meal_record(self, user_id: str, meal_id: str) -> Any | None: ...
    def list_meal_catalog_items(self, *, locale: str, slot: str | None = None, limit: int = 100) -> list[Any]: ...
    def get_meal_catalog_item(self, meal_id: str) -> Any | None: ...
    def save_meal_observation(self, observation: Any) -> None: ...
    def list_meal_observations(self, user_id: str) -> list[Any]: ...
    def save_validated_meal_event(self, event: Any) -> None: ...
    def list_validated_meal_events(self, user_id: str) -> list[Any]: ...
    def get_validated_meal_event(self, user_id: str, event_id: str) -> Any | None: ...
    def save_nutrition_risk_profile(self, profile: Any) -> None: ...
    def list_nutrition_risk_profiles(self, user_id: str) -> list[Any]: ...
    def get_nutrition_risk_profile(self, user_id: str, event_id: str) -> Any | None: ...


class FoodRepositoryProtocol(Protocol):
    def list_canonical_foods(self, *, locale: str, slot: str | None = None, limit: int = 100) -> list[Any]: ...
    def get_canonical_food(self, food_id: str) -> Any | None: ...
    def find_food_by_name(self, *, locale: str, name: str) -> Any | None: ...


class ClinicalRepositoryProtocol(Protocol):
    def save_biomarker_readings(self, user_id: str, readings: list[Any]) -> None: ...
    def list_biomarker_readings(self, user_id: str) -> list[Any]: ...
    def save_symptom_checkin(self, checkin: Any) -> Any: ...
    def list_symptom_checkins(
        self,
        *,
        user_id: str,
        start_at: datetime | None = None,
        end_at: datetime | None = None,
        limit: int = 200,
    ) -> list[Any]: ...


class MedicationRepositoryProtocol(Protocol):
    def list_medication_regimens(self, user_id: str, *, active_only: bool = False) -> list[Any]: ...
    def save_medication_regimen(self, regimen: Any) -> None: ...
    def get_medication_regimen(self, *, user_id: str, regimen_id: str) -> Any | None: ...
    def delete_medication_regimen(self, *, user_id: str, regimen_id: str) -> bool: ...
    def save_medication_adherence_event(self, event: Any) -> Any: ...
    def list_medication_adherence_events(
        self,
        *,
        user_id: str,
        start_at: datetime | None = None,
        end_at: datetime | None = None,
    ) -> list[Any]: ...


class ReminderRepositoryProtocol(Protocol):
    def save_reminder_event(self, event: Any) -> None: ...
    def get_reminder_event(self, event_id: str) -> Any | None: ...
    def list_reminder_events(self, user_id: str) -> list[Any]: ...
    def list_reminder_notification_preferences(
        self,
        *,
        user_id: str,
        scope_type: str | None = None,
        scope_key: str | None = None,
    ) -> list[Any]: ...
    def replace_reminder_notification_preferences(
        self,
        *,
        user_id: str,
        scope_type: str | None = None,
        scope_key: str | None = None,
        preferences: list[Any],
    ) -> list[Any]: ...
    def list_scheduled_notifications(
        self,
        *,
        reminder_id: str | None = None,
        user_id: str | None = None,
    ) -> list[Any]: ...
    def save_scheduled_notification(self, notification: Any) -> Any: ...
    def lease_due_scheduled_notifications(self, *, now: Any, limit: int = 100) -> list[Any]: ...
    def get_reminder_notification_endpoint(self, *, user_id: str, channel: str) -> Any | None: ...
    def append_notification_log(self, entry: Any) -> Any: ...
    def cancel_scheduled_notifications_for_reminder(self, reminder_id: str) -> int: ...
    def enqueue_alert(self, message: Any) -> list[Any]: ...
    def list_reminder_notification_endpoints(self, *, user_id: str) -> list[Any]: ...
    def replace_reminder_notification_endpoints(self, *, user_id: str, endpoints: list[Any]) -> list[Any]: ...
    def list_notification_logs(
        self,
        *,
        reminder_id: str | None = None,
        scheduled_notification_id: str | None = None,
    ) -> list[Any]: ...
    def get_mobility_reminder_settings(self, user_id: str) -> Any | None: ...
    def save_mobility_reminder_settings(self, settings: Any) -> Any: ...


class ClinicalCardRepositoryProtocol(Protocol):
    def save_clinical_card(self, card: Any) -> Any: ...
    def list_clinical_cards(self, *, user_id: str, limit: int = 50) -> list[Any]: ...
    def get_clinical_card(self, *, user_id: str, card_id: str) -> Any | None: ...


class WorkflowRepositoryProtocol(Protocol):
    def list_tool_role_policies(
        self,
        *,
        role: str | None = None,
        agent_id: str | None = None,
        tool_name: str | None = None,
        enabled_only: bool = False,
    ) -> list[Any]: ...
    def save_tool_role_policy(self, record: Any) -> Any: ...
    def get_tool_role_policy(self, policy_id: str) -> Any | None: ...
    def save_workflow_timeline_event(self, event: Any) -> Any: ...
    def list_workflow_timeline_events(
        self,
        *,
        correlation_id: str | None = None,
        user_id: str | None = None,
    ) -> list[Any]: ...


class CatalogRepositoryProtocol(Protocol):
    def save_recommendation(self, user_id: str, payload: dict[str, Any]) -> None: ...
    def list_canonical_foods(self, *, locale: str, slot: str | None = None, limit: int = 100) -> list[Any]: ...
    def get_canonical_food(self, food_id: str) -> Any | None: ...
    def find_food_by_name(self, *, locale: str, name: str) -> Any | None: ...
    def get_meal_record(self, user_id: str, meal_id: str) -> Any | None: ...
    def list_meal_records(self, user_id: str) -> list[Any]: ...
    def save_biomarker_readings(self, user_id: str, readings: list[Any]) -> None: ...
    def save_recommendation_interaction(self, interaction: Any) -> Any: ...
    def list_recommendation_interactions(self, user_id: str, *, limit: int = 200) -> list[Any]: ...
    def get_preference_snapshot(self, user_id: str) -> Any | None: ...
    def save_preference_snapshot(self, snapshot: Any) -> Any: ...
    def save_suggestion_record(self, user_id: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    def list_suggestion_records(self, user_id: str, limit: int = 20) -> list[dict[str, Any]]: ...
    def get_suggestion_record(self, user_id: str, suggestion_id: str) -> dict[str, Any] | None: ...


class ProfileRepositoryProtocol(Protocol):
    def get_health_profile(self, user_id: str) -> Any | None: ...
    def save_health_profile(self, profile: Any) -> Any: ...
    def get_health_profile_onboarding_state(self, user_id: str) -> Any | None: ...
    def save_health_profile_onboarding_state(self, state: Any) -> Any: ...


class AlertRepositoryProtocol(Protocol):
    def list_alert_records(self, alert_id: str | None = None) -> list[Any]: ...
