from typing import Any

def configure(*args: Any, **kwargs: Any) -> None: ...

def warn(*args: Any, **kwargs: Any) -> None: ...

def error(*args: Any, **kwargs: Any) -> None: ...

class LogfireLoggingHandler:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
